# Find our git repo: https://github.com/loopbio/opencv-feedstock

{% set version = "3.2.0" %}

package:
  name: opencv
  version: {{ version }}

source:
  fn: opencv-{{ version }}.tar.gz
  url: https://github.com/opencv/opencv/archive/{{ version }}.tar.gz
  sha256: b9d62dfffb8130d59d587627703d5f3e6252dce4a94c1955784998da7a39dd35
  patches:
    # Safe mutex unlocking for loopb's KeyThread
    - gtk-safe-mutex-unlock.patch

build:
  number: 1
  skip: true  # [not (linux and np>=111)]
  features:
    - ffmpeg
    - gtk2

requirements:
  build:
    - python
    - toolchain
    # For sha256 comparisons of opencv_contrib
    - openssl 1.0.*         # [unix]
    # For downloading opencv_contrib
    - curl
    - cmake
    - numpy x.x
    - hdf5 1.8.17|1.8.17.*  # [unix]
    - eigen 3.2.*
    - jasper                # [unix]
    - zlib 1.2.*
    - jpeg 9*
    - libtiff 4.0.*
    - libwebp 0.5.*
    - harfbuzz 1.3.*        # [unix]
    - libpng >=1.6.23,<1.7

    - gtk2
    # Needed as the centos gtk does not play well with conda-forge libpng
    # Not in default or conda-forge, so need a channel before rerendering
    # This is at the moment a hack to allow *building* using newer gtk2 + libpng

    # ffmpeg support (from conda-forge)
    - ffmpeg

  run:
    - python
    - numpy x.x
    - hdf5 1.8.17|1.8.17.*  # [unix]
    - jasper                # [unix]
    - zlib 1.2.*
    - jpeg 9*
    - libwebp 0.5.*
    - harfbuzz 1.3.*        # [unix]
    - libtiff 4.0.*
    - libpng >=1.6.23,<1.7
    # GTK2
    # In general, we won't need this at runtime as long as system gtk2 is installed
    - gtk2-feature    # TODO: this concrete package should not be a requirement, defeats the purpose of features
    - gtk2
    # FFMPEG
    - ffmpeg-feature  # TODO: this concrete package should not be a requirement, defeats the purpose of features
    - ffmpeg

test:
    imports:
      - cv2
      - cv2.xfeatures2d

    commands:
        # Verify dynamic libraries on all systems
        {% set opencv_libs = [
            "aruco",
            "bgsegm",
            "calib3d",
            "ccalib",
            "core",
            "datasets",
            "dnn",
            "dpm",
            "face",
            "features2d",
            "flann",
            "fuzzy",
            "highgui",
            "imgcodecs",
            "imgproc",
            "line_descriptor",
            "ml",
            "objdetect",
            "optflow",
            "phase_unwrapping",
            "photo",
            "plot",
            "reg",
            "rgbd",
            "saliency",
            "shape",
            "stereo",
            "stitching",
            "structured_light",
            "superres",
            "surface_matching",
            "text",
            "tracking",
            "video",
            "videoio",
            "videostab",
            "xfeatures2d",
            "ximgproc",
            "xobjdetect",
            "xphoto"
        ] %}
        {% for each_opencv_lib in opencv_libs %}
        - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.dylib                        # [osx]
        - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}.so                           # [linux]
        - if not exist %PREFIX%\\Library\\bin\\opencv_{{ each_opencv_lib }}320.dll exit 1  # [win]
        {% endfor %}
        - test -f $PREFIX/lib/libopencv_bioinspired.dylib  # [osx]
        - test -f $PREFIX/lib/libopencv_bioinspired.so     # [linux]
        - test -f $PREFIX/lib/libopencv_hdf.dylib          # [osx]
        - test -f $PREFIX/lib/libopencv_hdf.so             # [linux]
        - test -f $PREFIX/lib/libopencv_freetype.dylib     # [osx]
        - test -f $PREFIX/lib/libopencv_freetype.so        # [linux]

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: Computer vision and machine learning software library.

extra:
  original-recipe-url: https://github.com/conda-forge/opencv-feedstock/tree/c8d7e0bea4c7c298a13b339d81088f0f564becf4
  original-recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
  recipe-url: https://github.com/loopbio/opencv-feedstock
  recipe-maintainers:
    - sdvillal


#
# We could switch to qt, which is maintained (albeit with some problems at the time of writing)
# in the conda/conda-forge ecosystem. However, loopb event thread (and possibly other stuff)
# does not work with qt at the moment, even if only using opencv higui.
#
