#
# Changes from conda-forge recipe:
#
#  - Disable non-linux builds.
#
#  - Explicitly enable C++11 on old compilers.
#
#  - Explicitly compile with IPP.
#
#  - Compile with TBB.
#
#  - Compile against libjpeg-turbo static.
#
#  - Use installed protobuf instead of compile it
#    (although this is still a liability and we should probably
#    just stop building the DNN module that remains unused for us).
#
#  - Expose thread_count and thread_type in opencv video capture.
#    Can be set with an envvar and queried via property.
#
#  - Disable GStreamer.
#    Otherwise it gets also linked to it, as it is
#    pulled by QT. We might actually want to use
#    this, but it is better to make sure ffmpeg
#    is the only video backend.
#
#  - Prepared to build against MKL.
#    But disabled (commented out mkl deps here + -DWITH_LAPACK=OFF)
#    I do not think BLAS/LAPACK are really used much out of
#    the DNN module, and last opencv release notes do claim
#    it does not make much difference anymore. If need to
#    bring back, use MKL or OpenBLAS, but do not request
#    the openblas feature.
#
#  - Put libs in /lib, not /lib64.
#
#  - Made many configuration parameters explicit in build.sh.
#    e.g. possible optimizations like CPU instruction support
#    or fast math, help for debugging etc.
#
#  - Better tests for video (seeking) and jpeg processing.
#
#  - List build information and linkages after success.
#
# There are interesting notes and links in my dear building diary.
#

{% set version = "3.4.3" %}
{% set build_number= "0" %}

package:
  name: opencv
  version: {{ version }}

source:
  - url: https://github.com/opencv/opencv/archive/{{ version }}.tar.gz
    fn: opencv-{{ version }}.tar.gz
    sha256: 4eef85759d5450b183459ff216b4c0fa43e87a4f6aa92c8af649f89336f002ec
    patches:
      # minimal patch to ensure we load our turbo header regardless of include dir order
      # otherwise opencv is using /include with higher priority than /include/libjpeg-turbo-prefixed
      # see https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html and the patch source
      - use-custom-turbo.patch
      # allow to set the number of threads and threading type used by ffmpeg decoders
      - expose-ffmpeg-thread-count.patch
      - expose-ffmpeg-thread-type.patch
  - url: https://github.com/opencv/opencv_contrib/archive/{{ version }}.tar.gz
    fn: opencv_contrib-{{ version }}.tar.gz
    sha256: 6dfb51326f3dfeb659128df952edecd45683626a965aa4a8e1e9c970c40fb636
    folder: opencv_contrib-{{ version }}

build:
  number: {{ build_number }}
  # Python2.7 support dropped: https://github.com/opencv/opencv/issues/8481
  skip: true  # [not linux]
  ignore_run_exports:
    - libjpeg-turbo

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config  # [not win]
  host:
    - python
    - numpy
    - hdf5
    - eigen 3.2.*
    - zlib
    - harfbuzz  # [unix]
    # libjpeg-turbo playing nice with libjpeg9:
    # (avoid file clobbering and same name global symbols interposition / preemption)
    - libjpeg-turbo 2.0.0 noclob_prefixed_gcc48_0
    - libpng
    - libwebp
    - libtiff
    - jasper  # [unix]
  # - mkl >=2018.0*
  # - mkl-include >=2018.0*
    - tbb-devel 2019.*
    - ffmpeg 4.0.* nonvidia_lgpl*  # [not win]
    - qt                           # [not osx]
    - protobuf  # N.B. current pin for TF is >=3.4.0, we let CF pin to float here
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - hdf5      # [unix]
    - zlib
    - harfbuzz  # [unix]
    - libpng
    - libwebp
    - libtiff
    - jasper  # [unix]
  # - mkl >=2018.0*
    - tbb 2019.*
  # - ffmpeg 4.0.*  # [not win]
    - qt            # [not osx]
    - protobuf  # N.B. current pin for TF is >=3.4.0, we let CF pin to float here

test:
    files:
      - opencv_frame_hashes.json
      - 687px-Mona_Lisa,_by_Leonardo_da_Vinci,_from_C2RMF_retouched.jpg
      - ensure_jpegturbo_opencv_plays_nicely_with_jpeg9.py
      - ensure_build_features.py
      - test_video_seek.py

    requires:
      - pillow    # so we make sure there is no symbol clash libjpeg-turbo jpeg 9
      - requests
      - certifi
      - pytest

    imports:
      - cv2
      - cv2.xfeatures2d

    commands:
        # first some info
        - python -c 'import cv2; print(cv2.getBuildInformation())'
        # Verify dynamic libraries on all systems
        # "dnn", "text", removed when DNN is left out
        {% set win_ver_lib = version|replace(".", "") %}
        {% set opencv_libs = [
            "aruco",
            "bgsegm",
            "bioinspired",
            "calib3d",
            "ccalib",
            "core",
            "datasets",
            "dnn",
            "dpm",
            "face",
            "features2d",
            "flann",
            "freetype",
            "fuzzy",
            "hdf",
            "highgui",
            "imgcodecs",
            "imgproc",
            "line_descriptor",
            "ml",
            "objdetect",
            "optflow",
            "phase_unwrapping",
            "photo",
            "plot",
            "reg",
            "rgbd",
            "saliency",
            "shape",
            "stereo",
            "stitching",
            "structured_light",
            "superres",
            "surface_matching",
            "text",
            "tracking",
            "video",
            "videoio",
            "videostab",
            "xfeatures2d",
            "ximgproc",
            "xobjdetect",
            "xphoto"
        ] %}
        {% for each_opencv_lib in opencv_libs %}
        - test -f $PREFIX/lib/libopencv_{{ each_opencv_lib }}${SHLIB_EXT}                  # [unix]
        - if not exist %PREFIX%\\Library\\bin\\opencv_{{ each_opencv_lib }}{{ win_ver_lib }}.dll exit 1  # [win]
        {% endfor %}
        - python ensure_build_features.py
        - python ensure_jpegturbo_opencv_plays_nicely_with_jpeg9.py 0  # segfaults FTW
        - python ensure_jpegturbo_opencv_plays_nicely_with_jpeg9.py 1
        - python -c 'import cv2; assert cv2.CAP_PROP_THREAD_COUNT == 5555'
        - python -c 'import cv2; assert cv2.CAP_PROP_THREAD_TYPE == 5556'
        - pytest test_video_seek.py
        # lastly some info
        - conda inspect linkages -p $PREFIX $PKG_NAME   # [unix]
        - python -c 'import cv2; print(cv2.getBuildInformation())'

about:
  home: http://opencv.org/
  license: BSD 3-clause
  summary: "Loopbio optimized OpenCV builds: https://github.com/loopbio/opencv-feedstock"

extra:
  recipe-maintainers:
    - sdvillal
  conda-forge-recipe-maintainers:
    - jakirkham
    - msarahan
    - patricksnape
    - zym1010
    - hajapy
    - ocefpaf
